esafirm/android-image-picker

imagepicker/src/main/res/values-it/strings.xml, imagepicker/src/main/res/values-ro/strings.xml, imagepicker/src/main/res/values/strings.xml
Added italian and romanian translations for the strings.xml file
=> added 2 translations

imagepicker/src/main/res/values/colors.xml
I decided to do it this way. Most usage for changing the color is, that the app colors (primary/accent) should be used.
=> Colors could be overridden by app colors.

imagepicker/src/main/res/values-ru/strings.xml, imagepicker/src/main/res/values-uk/strings.xml
Issue: https://github.com/esafirm/android-image-picker/issues/25
=> Russian translation fix, Ukrainian translation

imagepicker/src/main/res/values-ko/strings.xml
Fixes "before pull request"
Thank you!
=> Add Korean translation.

imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerActivity.java
Removing this code block is needed to fix snackbar.
=> Fixes #49, Remove unnecessary code in showing snackBarView.

imagepicker/src/main/res/values-fr/strings.xml
=> Add french translation

imagepicker/src/main/res/values-de/strings.xml
Added German translation. I also extracted some hard-coded string resources of the sample app so they get translated.
=> Added German translation

imagepicker/src/main/java/com/esafirm/imagepicker/adapter/ImagePickerAdapter.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImageFileLoader.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePicker.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerActivity.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerConfig.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerPresenter.java, imagepicker/src/main/java/com/esafirm/imagepicker/helper/ImagePickerUtils.java, imagepicker/src/main/res/layout/ef_imagepicker_item_image.xml, imagepicker/src/main/res/values/strings.xml, sample/src/main/java/com/esafirm/sample/MainActivity.java, sample/src/main/res/layout/activity_main.xml
I made some changes to the image picker that add basic video support:
- Add ImagePicker.includeVideo(boolean)
- Add a "Video" label for video thumbnails (see screenshot)
- Add Include Video option to sample app
=> Add basic video support

imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePicker.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerActivity.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerConfig.java, imagepicker/src/main/java/com/esafirm/imagepicker/helper/ConfigUtils.java, sample/src/main/java/com/esafirm/sample/MainActivity.java, sample/src/main/java/com/esafirm/sample/MainFragment.java
This is the PR for the following issue :
https://github.com/esafirm/android-image-picker/issues/131
=> Make toolbar done button customizable

imagepicker/src/main/java/com/esafirm/imagepicker/helper/ImagePickerUtils.java
Will close https://github.com/esafirm/android-image-picker/issues/153
=> Fix crash on extracting mime type

imagepicker/src/main/res/values-pt-br/strings.xml
=> Translation to PT-br

imagepicker/src/main/java/com/esafirm/imagepicker/features/ImageFileLoader.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePicker.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerConfig.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerPresenter.java
Added configuration to allow the user to include or exclude animation (gif) files. Fixes #170
=> Adding option to exclude gif files.

imagepicker/src/main/java/com/esafirm/imagepicker/helper/ImagePickerUtils.java
The camera will create the file for you. No need to create it beforehand. Added current millisecond to filename, so the file should be unique.
Also added fallback mechanism, if file exists.
=> 0 byte file bug fixed

build.gradle, gradle/wrapper/gradle-wrapper.properties, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImageFileLoader.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePicker.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerConfig.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerPresenter.java, sample/src/main/java/com/esafirm/sample/MainActivity.java, sample/src/main/res/layout/activity_main.xml
I made some changes to the image picker that add only video support:
- Add ImagePicker.onlyVideo(boolean)
- Add Only video option to sample app
=> Support only video

README.md, imagepicker/src/main/AndroidManifest.xml, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePicker.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerComponentHolder.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerConfig.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerConfigFactory.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerFragment.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerPresenter.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/camera/DefaultCameraModule.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/fileloader/DefaultImageFileLoader.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/fileloader/ImageFileLoader.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/imageloader/ImageLoader.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/recyclers/RecyclerViewManager.java, imagepicker/src/main/java/com/esafirm/imagepicker/helper/ConfigUtils.java, imagepicker/src/main/java/com/esafirm/imagepicker/helper/ImagePickerFileProvider.java, imagepicker/src/main/java/com/esafirm/imagepicker/helper/ImagePickerUtils.java, sample/src/main/java/com/esafirm/sample/MainActivity.java
1. Refactor custom `ImageLoader` config
2. Make `ImageFileLoader` configurable.
Close https://github.com/esafirm/android-image-picker/issues/237
=> Faster image file loader

.circleci/config.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties, imagepicker/build.gradle, imagepicker/src/main/java/com/esafirm/imagepicker/adapter/FolderPickerAdapter.java, imagepicker/src/main/java/com/esafirm/imagepicker/adapter/ImagePickerAdapter.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerFragment.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/camera/DefaultCameraModule.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/fileloader/DefaultImageFileLoader.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/fileloader/ImageFileLoader.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/imageloader/DefaultImageLoader.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/imageloader/ImageLoader.java, imagepicker/src/main/java/com/esafirm/imagepicker/helper/ImagePickerUtils.java, imagepicker/src/main/java/com/esafirm/imagepicker/model/Image.java, sample/build.gradle, sample/src/main/java/com/esafirm/sample/GrayscaleImageLoader.java
Add Android Q support
1. Fix failed to create image file https://github.com/esafirm/android-image-picker/pull/262
2. Handle external scoped https://github.com/bumptech/glide/issues/3896
3. Bump target SDK to Q
4. Bump Glide to 4.11.0
5. Update Circle CI 
Close https://github.com/esafirm/android-image-picker/issues/263
Close https://github.com/esafirm/android-image-picker/issues/266
=> Android q support

CHANGELOG.md, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerFragment.java, imagepicker/src/main/java/com/esafirm/imagepicker/view/SnackBarView.java, imagepicker/src/main/res/layout/ef_fragment_image_picker.xml, sample/build.gradle, sample/src/main/AndroidManifest.xml
Closes https://github.com/esafirm/android-image-picker/issues/241
=> Fix unclickable snackbar

imagepicker/src/main/java/com/esafirm/imagepicker/features/fileloader/DefaultImageFileLoader.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/imageloader/DefaultImageLoader.java, imagepicker/src/main/java/com/esafirm/imagepicker/model/Image.java, sample/src/main/java/com/esafirm/sample/ImageViewerActivity.java
Make convenient method to get `Uri` from `Image`
Close https://github.com/esafirm/android-image-picker/issues/278
Close https://github.com/esafirm/android-image-picker/issues/276
=> add getUri in Image for convenient

imagepicker/src/main/java/com/esafirm/imagepicker/features/camera/DefaultCameraModule.java
use MediaStore to support Android Q
=> fix for https://github.com/esafirm/android-image-picker/issues/280

CHANGELOG.md, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerFragment.java, imagepicker/src/main/java/com/esafirm/imagepicker/features/camera/DefaultCameraModule.java
=> Fix camera on q

.github/workflows/android.yml
Test lab should not trigger in this PR
=> only run testlab on master

imagepicker/src/main/res/values-ja/strings.xml
=> Japanese support

build.gradle, imagepicker/src/main/java/com/esafirm/imagepicker/helper/ImagePickerUtils.kt
- set target and compile SDK to 30
- bump AGP to 4.1.3
- bump Kotlin to 1.4.32
=> set target and compile sdk to 30

imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerActivity.kt, sample/src/androidTest/java/com/esafirm/sample/CameraOnlyTest.kt
Close https://github.com/esafirm/android-image-picker/issues/359
=> fix on crash camera only cancel

imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerFragment.kt, imagepicker/src/main/java/com/esafirm/imagepicker/features/fileloader/DefaultImageFileLoader.kt, sample/src/androidTest/java/com/esafirm/sample/helper/ImageGeneratorScenario.kt, sample/src/androidTest/java/com/esafirm/sample/utils/ImageGenerator.kt
1. Fix sort on Q+
2. Add image generator helper for load test
3. Fix loading state
Close: https://github.com/esafirm/android-image-picker/issues/367
=> fix sort on q

imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerActivity.kt
when every i open the camera and back press it crash the app
=> camera only back press crash fixed

imagepicker/src/main/res/values-sv-rSE/strings.xml
Based on the already translated string in #340
closes #340
=> Add Swedish translation

imagepicker/src/main/res/values-ca/strings.xml, imagepicker/src/main/res/values-es-rES/strings.xml
Adds translations for spanish and catalan languages
=> Add spanish and catalan translations

imagepicker/src/main/res/values/strings.xml
=> Add camera permission english string (#405)

.gitignore, sample/build.gradle, sample/src/androidTest/AndroidManifest.xml, sample/src/androidTest/java/com/esafirm/sample/CameraOnPickerTest.kt, sample/src/androidTest/java/com/esafirm/sample/CameraOnlyTest.kt, sample/src/androidTest/java/com/esafirm/sample/CustomUiTest.kt, sample/src/androidTest/java/com/esafirm/sample/PickImageFolderMode.kt, sample/src/androidTest/java/com/esafirm/sample/PickImageFragmentTest.kt, sample/src/androidTest/java/com/esafirm/sample/PickImageSingleTest.kt
The current CI is failed in building the sample because it cannot find Barista dependency.
=> Fix - Change barista dependency

.github/workflows/android.yml, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, imagepicker/build.gradle, imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerActivity.kt, sample/build.gradle, sample/src/androidTest/AndroidManifest.xml, sample/src/androidTest/java/com/esafirm/sample/CameraOnPickerTest.kt, sample/src/androidTest/java/com/esafirm/sample/CameraOnlyTest.kt, sample/src/androidTest/java/com/esafirm/sample/CustomUiTest.kt, sample/src/androidTest/java/com/esafirm/sample/PickImageFolderMode.kt, sample/src/androidTest/java/com/esafirm/sample/PickImageFragmentTest.kt, sample/src/androidTest/java/com/esafirm/sample/PickImageSingleTest.kt, sample/src/androidTest/java/com/esafirm/sample/PickImageTest.kt, sample/src/androidTest/java/com/esafirm/sample/helper/ImageGeneratorScenario.kt, sample/src/main/AndroidManifest.xml
- Update AGP version
- Update Kotlin version
- Add some workaround to make connected check work (issue with Android 12) https://issuetracker.google.com/issues/182098106
- Change the JDK version to 11 in Github Action
- And others adjustments around above changes
=> upgrade AGP and Kotlin version

build.gradle, imagepicker/src/main/java/com/esafirm/imagepicker/helper/LocaleManager.kt, imagepicker/src/main/java/com/esafirm/imagepicker/helper/ViewUtils.kt, sample/build.gradle
Removing code that have unused min SDK check.
=> Code cleanup

docs/save_location.md
- use Kotlin instead of Java in the docs
- reflect current API
- align with existing sample
=> update `save_location.md` to use Kotlin and reflect current API

docs/custom_components.md
- use Kotlin instead of Java in the docs
- reflect current API
- align with existing sample
=> update `custom_components.md` to use Kotlin and reflect current API
