- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePicker.java
In the need of trying to use a custom `ImagePickerActivity` (or an extension) I would like to be able to override `ImagePicker#getIntent()` and access my current config to launch the activity.
The getter is for general purpose.
> Expose config

- imagepicker/src/main/java/com/esafirm/imagepicker/adapter/ImagePickerAdapter.java
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerActivity.java
- imagepicker/src/main/java/com/esafirm/imagepicker/features/recyclers/RecyclerViewManager.java
- imagepicker/src/main/java/com/esafirm/imagepicker/listeners/OnImageClickListener.java
If it reaches the limit, reselection will show "selection limit" toast.
Also this commit fixes inconsistent condition of OnImageClickListener caller and
callee.
> Fix reselection in MODE_MULTIPLE

- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImageFileLoader.java
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePicker.java
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerActivity.java
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerConfig.java
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerPresenter.java
Added option to exclude files from being display by providing either `File` or `Image` instances representing the path of the image. Closes #99.
> Added option to exclude files from being display

- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImageFileLoader.java
As stated in the issue I opened before 2 weeks: https://github.com/esafirm/android-image-picker/issues/133 and by another user: https://github.com/esafirm/android-image-picker/issues/138
The problem was relying in the check of `file.exists()` on each file. caused too much I/O blocking operations.
The image picker now loads instantly instead of taking many seconds (11 seconds in my case). Depends on the amount of files in the user's gallery.
> Fixed the very long delay when initating the folder gallery picker

- imagepicker/src/main/java/com/esafirm/imagepicker/adapter/ImagePickerAdapter.java
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePicker.java
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerActivity.java
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerConfig.java
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerFragment.java
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerInteractionListener.java
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerPresenter.java
- imagepicker/src/main/java/com/esafirm/imagepicker/features/recyclers/OnBackAction.java
- imagepicker/src/main/java/com/esafirm/imagepicker/features/recyclers/RecyclerViewManager.java
- imagepicker/src/main/java/com/esafirm/imagepicker/helper/IpCrasher.java
- imagepicker/src/main/res/layout/ef_activity_image_picker.xml
- imagepicker/src/main/res/layout/ef_fragment_image_picker.xml
- sample/src/main/AndroidManifest.xml
- sample/src/main/java/com/esafirm/sample/CustomUIActivity.java
- sample/src/main/java/com/esafirm/sample/MainActivity.java
- sample/src/main/res/layout/activity_custom_ui.xml
- sample/src/main/res/layout/activity_main.xml
…called ImagePickerFragment. Keeps the toolbar and menus in the Activity.
This also adds a custom Activity to the sample app that is very similar to ImagePickerActivity, but includes a larger-sized preview.
Replaces #164, which I sort-of-accidentally squished due to some Git challenges.
> Moves ImagePickerActivity's logic into a Fragment

- build.gradle
- imagepicker/build.gradle
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePicker.java
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerFragment.java
- sample/build.gradle
- sample/src/main/AndroidManifest.xml
- sample/src/main/java/com/esafirm/sample/MainActivity.java
- sample/src/main/java/com/esafirm/sample/SampleApplication.java
I am using android-image-picker inside an app were we are using [leakcanary](https://github.com/square/leakcanary) in debug builds. I received a memory leak warning about the ContentResolver.
The reason is, that the `ContentObserver` is registered in `onStart`, but unregistered in `onDestroy`.
How to reproduce: 
1. Use leakcanary (first commit) and start sample app
2. Start the image picker
3. Press back
4. Start image picker again
5. You'll see leakcanary dumping the heap
I tested a bit with the sample and it doesn't seem to introduce new bugs.
> Fix - Memory leak ContentResolver

- .circleci/config.yml
- imagepicker/build.gradle
- imagepicker/src/main/java/com/esafirm/imagepicker/features/imageloader/DefaultImageLoader.java
- sample/build.gradle
- setup.sh
Updated glide 4.9.0, and fixed [issue 196](https://github.com/esafirm/android-image-picker/issues/196)
> Update glide 4.9.0

- setup.sh
Changed accepting SDK license for jitpack in ```setup.sh``` to
```yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;28.0.3" ```
> Changed accepting SDK license for jitpack to more correct

- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePicker.java
- imagepicker/src/main/java/com/esafirm/imagepicker/helper/LocaleManager.java
Fix Locale Manager getLanguage() issue, 
If devices in Taiwan or Hong Kong area, 
it's the language code should be zh-TW or zh-HK.
> Fix Locale code for language function

- imagepicker/src/main/java/com/esafirm/imagepicker/adapter/ImagePickerAdapter.java
- imagepicker/src/main/java/com/esafirm/imagepicker/helper/ImagePickerUtils.java
- imagepicker/src/main/res/values-da/strings.xml
- imagepicker/src/main/res/values-de/strings.xml
- imagepicker/src/main/res/values/strings.xml
- Show the duration label as HH:mm:ss or mm:ss format.
https://github.com/esafirm/android-image-picker/issues/270
> Show the video duration on the image picker.

- imagepicker/src/main/java/com/esafirm/imagepicker/features/fileloader/DefaultImageFileLoader.java
- imagepicker/src/main/java/com/esafirm/imagepicker/features/imageloader/DefaultImageLoader.java
Currently the `folderMode` isn't as useful as it could be. Folders are sorted in whatever order the HashMap happens to produce from the `values()` call. It doesn't result in a great user experience if the user has several albums.
This change has it sort the folders by the dates the photos were added, in order of newest to oldest.
> Sort folders by date added

- imagepicker/src/main/java/com/esafirm/imagepicker/features/fileloader/DefaultImageFileLoader.java
`Folder` and `Image` are made kotlin data models in the previous release. Still, the client code (`DefaultImageFileLoader`) is in Java, and it creates an instance of these models without `not null` validation.
This PR fixes #310, #311, #315
> Fix for folder name, image name NPE 

- imagepicker/src/main/java/com/esafirm/imagepicker/adapter/ImagePickerAdapter.kt
- imagepicker/src/main/java/com/esafirm/imagepicker/features/fileloader/DefaultImageFileLoader.java
- imagepicker/src/main/java/com/esafirm/imagepicker/helper/ImagePickerUtils.java
Fix Android Q cannot open gallery when the directory contains video
> Fix display video duration cause app crash when targeting to sdk 29 and fix display media file under root in folder mode

- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerLauncher.kt
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerSavePath.kt
- imagepicker/src/main/java/com/esafirm/imagepicker/features/camera/DefaultCameraModule.kt
- sample/build.gradle
- sample/src/androidTest/java/com/esafirm/sample/CameraOnlyTest.kt
- sample/src/androidTest/java/com/esafirm/sample/utils/Views.kt
- sample/src/main/java/com/esafirm/sample/CustomUIActivity.kt
- sample/src/main/java/com/esafirm/sample/MainActivity.kt
- sample/src/main/java/com/esafirm/sample/MainFragment.kt
- sample/src/main/res/layout/activity_main.xml
- sample/src/main/res/layout/fragment_main.xml
- sample/src/main/res/values/styles.xml
Make `ImagePickerLauncher` a class instead a function/lambda 
This also makes a unified launcher for the camera only and image picker 
Ex:
```kotlin
val launcher = registerImagePicker {
// handler result here
}
// Call image picker
launcher.launch()
// Call with custom config
launcher.launch(ImagePickerConfig { 
doneButtonText = "Selesai"
})
// Call camera only
launcher.launch(CameraOnlyConfig())
```
> Refactor launcher

- imagepicker/src/main/AndroidManifest.xml
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerFragment.java
- imagepicker/src/main/java/com/esafirm/imagepicker/helper/ImagePickerPreferences.java
- imagepicker/src/main/res/values-ar/strings.xml
- imagepicker/src/main/res/values-da/strings.xml
- imagepicker/src/main/res/values-de/strings.xml
- imagepicker/src/main/res/values-fr/strings.xml
- imagepicker/src/main/res/values-in/strings.xml
- imagepicker/src/main/res/values-it/strings.xml
- imagepicker/src/main/res/values-ja/strings.xml
- imagepicker/src/main/res/values-ko/strings.xml
- imagepicker/src/main/res/values-pt-rBR/strings.xml
- imagepicker/src/main/res/values-ro/strings.xml
- imagepicker/src/main/res/values-ru/strings.xml
- imagepicker/src/main/res/values-tr/strings.xml
- imagepicker/src/main/res/values-uk/strings.xml
- imagepicker/src/main/res/values-zh-rCN/strings.xml
- imagepicker/src/main/res/values-zh-rTW/strings.xml
- imagepicker/src/main/res/values/strings.xml
In android11 "write_external_storage" permission is ignored. 
So I change to use "read" permission instead of "write" on scoped storage devices. 
Related 
https://github.com/esafirm/android-image-picker/issues/361, https://github.com/esafirm/android-image-picker/issues/341
> Use READ_EXTERNAL_STORAGE instead of WRITE on android11.

- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerLauncher.kt
- sample/src/main/java/com/esafirm/sample/CustomUIActivity.kt
- sample/src/main/java/com/esafirm/sample/MainFragment.kt
- The application crash because the fragment is not attached to context yet when initializing ImagePickerLauncher
> fix fragment not attached to context exception

- imagepicker/src/main/res/values-vi/strings.xml
- imagepicker/src/main/res/values/strings.xml
Hi, I would like to add Vietnamese to this project. Thanks.
> add vi language

- build.gradle
- imagepicker/src/main/AndroidManifest.xml
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerFragment.kt
- sample/build.gradle
- sample/src/main/AndroidManifest.xml
- Closes #403 
- Set compile and target sdk version 33
- to use READ_MEDIA_IMAGES permission
- Check READ_MEDIA_IMAGES permission is granted instead of WRITE_EXTERNAL_STORAGE when device is Android13 or later
> Add permission check for android13

- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerActivity.kt
Removed onActivityResult which is deprecated
> fix deprecated pickCamera

- build.gradle
- imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerFragment.kt
Fix the image count issue in the toolbar when the folder mode is selected.
Image count is not showing properly in the folder mode when moved from one folder to another.
Steps:
1. Enable folder mode
2. Open Custom Ui image picker
3. Select any number of images and click back
4. Open another folder
5. The toolbar shows "Folder" instead of image count
When opening different folders, the topbar should display the selected image count.
https://user-images.githubusercontent.com/20037228/196470226-f54a2796-4598-4a32-91d7-c9d51b55505c.mp4
https://user-images.githubusercontent.com/20037228/196470466-0a1a4d63-b9b1-4b55-910c-94151ab75841.mp4
Please let me know if you have any feedback.
Thank you!
> BugFix: Image count visible in the folder mode when moved from one folder to another
